-- =============================================================
-- Migration: nhật ký điểm danh theo NGÀY (chạy 1 lần trong SQL Editor)
-- Mỗi lần điểm danh 1 buổi vào 1 ngày = 1 dòng cho mỗi học viên.
-- Chỉ dòng present = true mới tính là "đã học".
-- =============================================================
create table if not exists attendance_records (
  id bigint generated by default as identity primary key,
  session_id bigint references schedule_sessions (id) on delete set null, -- giữ điểm danh dù buổi bị xóa
  student_id bigint references students (id) on delete cascade,
  date text not null,                       -- ngày học (YYYY-MM-DD)
  present boolean not null default true,
  created_at timestamptz not null default now(),
  unique (session_id, student_id, date)
);
alter table attendance_records enable row level security;
drop policy if exists "anon full access" on attendance_records;
create policy "anon full access" on attendance_records for all to anon using (true) with check (true);
