-- =============================================================
-- EduFlow AI (AIhoclaptrinh) — Supabase schema + seed data
-- Chạy 1 lần trong Supabase Dashboard → SQL Editor → New query
-- =============================================================

-- ---------- Tables ----------
create table if not exists students (
  id bigint generated by default as identity primary key,
  name text not null,
  email text default '',
  phone text default '',
  grade text default '',
  homeroom text default '',
  attendance int,
  gpa text default '',
  status text not null default 'Active' check (status in ('Active', 'At risk', 'Inactive')),
  cycle int not null default 10,
  fee text default '',
  created_at timestamptz not null default now()
);

create table if not exists payments (
  id bigint generated by default as identity primary key,
  student_id bigint not null references students (id) on delete cascade,
  date text not null,          -- DD/MM/YYYY (khớp shape của prototype)
  sessions int not null default 10,
  amount text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists courses (
  id bigint generated by default as identity primary key,
  subject text not null default 'CS' check (subject in ('Math', 'Science', 'English', 'History', 'Arts', 'CS')),
  name text not null,
  teacher text default '—',
  schedule text default '—',
  students int not null default 0,
  avg text not null default '—',
  progress int not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists schedule_sessions (
  id bigint generated by default as identity primary key,
  day int not null default 0 check (day between 0 and 4),   -- 0 = Thứ Hai … 4 = Thứ Sáu
  slot text not null default '07:30–09:00',
  name text not null,
  room text default '—',
  subject text not null default 'CS',
  student_ids bigint[] not null default '{}',
  attendance jsonb not null default '{}'::jsonb,            -- { "studentId": true }
  created_at timestamptz not null default now()
);

create table if not exists zalo_links (
  id bigint generated by default as identity primary key,
  code text not null default '',
  student_name text not null,
  token text default '',
  chat_id text default '',
  status text not null default 'Connected' check (status in ('Connected', 'Pending', 'Not linked')),
  last_msg text default '—',
  created_at timestamptz not null default now()
);

create table if not exists threads (
  id bigint generated by default as identity primary key,
  from_name text not null,
  role text default '',
  subject text default '—',
  preview text default '',
  time_label text default 'Just now',
  unread boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists app_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb
);

-- ---------- RLS ----------
-- ⚠️ LƯU Ý BẢO MẬT: app v1 chưa có đăng nhập nên policy dưới đây mở full
-- quyền cho anon key (ai có link app đều đọc/ghi được). Khi cần khoá thật:
-- thêm Supabase Auth rồi đổi "to anon" thành "to authenticated".
alter table students enable row level security;
alter table payments enable row level security;
alter table courses enable row level security;
alter table schedule_sessions enable row level security;
alter table zalo_links enable row level security;
alter table threads enable row level security;
alter table app_settings enable row level security;

drop policy if exists "anon full access" on students;
create policy "anon full access" on students for all to anon using (true) with check (true);
drop policy if exists "anon full access" on payments;
create policy "anon full access" on payments for all to anon using (true) with check (true);
drop policy if exists "anon full access" on courses;
create policy "anon full access" on courses for all to anon using (true) with check (true);
drop policy if exists "anon full access" on schedule_sessions;
create policy "anon full access" on schedule_sessions for all to anon using (true) with check (true);
drop policy if exists "anon full access" on zalo_links;
create policy "anon full access" on zalo_links for all to anon using (true) with check (true);
drop policy if exists "anon full access" on threads;
create policy "anon full access" on threads for all to anon using (true) with check (true);
drop policy if exists "anon full access" on app_settings;
create policy "anon full access" on app_settings for all to anon using (true) with check (true);

-- ---------- Seed data (giống hệt prototype) ----------
insert into students (id, name, email, phone, grade, homeroom, attendance, gpa, status, cycle, fee) values
  (1, 'Ava Thompson', 'ava.t@aihoclaptrinh.vn', '0901 234 567', '10', '10-B · Ms. Hale', 97, '3.82', 'Active', 10, '1.200.000₫'),
  (2, 'Jordan Ellis', 'jordan.e@aihoclaptrinh.vn', '0902 345 678', '9', '9-A · Mr. Cole', 78, '2.61', 'At risk', 10, ''),
  (3, 'Priya Nair', 'priya.n@aihoclaptrinh.vn', '', '11', '11-C · Dr. Um', 84, '3.10', 'At risk', 10, '1.200.000₫'),
  (4, 'Marcus Webb', 'marcus.w@aihoclaptrinh.vn', '', '12', '12-A · Ms. Ford', 95, '3.65', 'Active', 12, '1.400.000₫'),
  (5, 'Sofia Marino', 'sofia.m@aihoclaptrinh.vn', '', '10', '10-B · Ms. Hale', 99, '3.94', 'Active', 10, '1.200.000₫'),
  (6, 'Noah Kim', 'noah.k@aihoclaptrinh.vn', '', '9', '9-D · Mr. Ruiz', 92, '3.41', 'Active', 8, '1.000.000₫'),
  (7, 'Lena Okafor', 'lena.o@aihoclaptrinh.vn', '', '10', '10-A · Mr. Sato', 90, '3.02', 'At risk', 10, '1.200.000₫'),
  (8, 'Theo Bright', 'theo.b@aihoclaptrinh.vn', '', '11', '11-B · Ms. Park', 66, '2.88', 'Inactive', 10, '1.200.000₫')
on conflict (id) do nothing;

insert into payments (student_id, date, sessions, amount) values
  (1, '02/06/2026', 10, '1.200.000₫'),
  (1, '08/07/2026', 10, '1.200.000₫'),
  (3, '15/06/2026', 10, '1.200.000₫'),
  (4, '20/06/2026', 12, '1.400.000₫')
on conflict do nothing;

insert into courses (id, subject, name, teacher, schedule, students, avg, progress) values
  (1, 'Math', 'Algebra II', 'Mr. D. Cole', 'Mon/Wed/Fri 9:00', 28, '81%', 64),
  (2, 'Science', 'Biology — Honors', 'Dr. A. Um', 'Tue/Thu 10:30', 24, '87%', 58),
  (3, 'English', 'American Literature', 'Ms. R. Park', 'Daily 8:00', 31, '84%', 71),
  (4, 'CS', 'Intro to Programming', 'Mr. K. Sato', 'Mon/Wed 13:00', 22, '90%', 52),
  (5, 'History', 'World History', 'Ms. J. Ford', 'Tue/Thu 9:00', 29, '79%', 66),
  (6, 'Arts', 'Studio Art Foundations', 'Ms. L. Hale', 'Fri 13:00', 18, '93%', 60)
on conflict (id) do nothing;

insert into schedule_sessions (id, day, slot, name, room, subject, student_ids, attendance) values
  (1, 0, '07:30–09:00', 'Python cơ bản', 'Phòng 1', 'CS', '{1,6,5}', '{"1": true, "6": true}'),
  (2, 0, '09:00–10:30', 'Toán tư duy', 'Phòng 2', 'Math', '{2,7}', '{}'),
  (3, 0, '19:30–21:00', 'Lập trình AI nâng cao', 'Online', 'CS', '{3,4,8}', '{"3": true, "4": true, "8": true}'),
  (4, 1, '09:00–10:30', 'Tiếng Anh giao tiếp', 'Phòng 1', 'English', '{5,1}', '{"5": true}'),
  (5, 1, '14:30–16:00', 'Scratch thiếu nhi', 'Phòng 2', 'Arts', '{}', '{}'),
  (6, 1, '21:00–22:30', 'Luyện đề Toán', 'Online', 'Math', '{2}', '{}'),
  (7, 2, '07:30–09:00', 'Python cơ bản', 'Phòng 1', 'CS', '{}', '{}'),
  (8, 2, '16:00–17:30', 'Web Frontend', 'Phòng 2', 'Science', '{}', '{}'),
  (9, 2, '19:30–21:00', 'Lập trình AI nâng cao', 'Online', 'CS', '{3,4,8}', '{}'),
  (10, 3, '09:00–10:30', 'Tiếng Anh giao tiếp', 'Phòng 1', 'English', '{}', '{}'),
  (11, 3, '14:30–16:00', 'Scratch thiếu nhi', 'Phòng 2', 'Arts', '{}', '{}'),
  (12, 3, '19:30–21:00', 'Data & AI cơ bản', 'Online', 'History', '{}', '{}'),
  (13, 4, '07:30–09:00', 'Python cơ bản', 'Phòng 1', 'CS', '{}', '{}'),
  (14, 4, '16:00–17:30', 'Web Frontend', 'Phòng 2', 'Science', '{}', '{}'),
  (15, 4, '21:00–22:30', 'Luyện đề Toán', 'Online', 'Math', '{}', '{}')
on conflict (id) do nothing;

insert into zalo_links (id, code, student_name, token, chat_id, status, last_msg) values
  (1, 'STU-1102', 'Ava Thompson', 'zbt_8f2k…Qx91', '7203441189', 'Connected', 'Điểm kiểm tra tuần — 2 h'),
  (2, 'STU-2041', 'Jordan Ellis', 'zbt_a51m…Tz04', '7198220457', 'Connected', 'Cảnh báo chuyên cần — 12 min'),
  (3, 'STU-1877', 'Priya Nair', 'zbt_c09p…Lk22', '7311058763', 'Pending', 'Lời mời liên kết — hôm qua'),
  (4, 'STU-1450', 'Sofia Marino', 'zbt_d73r…Mn58', '7255903312', 'Connected', 'Thông báo học phí — T2'),
  (5, 'STU-1621', 'Noah Kim', '', '', 'Not linked', '—'),
  (6, 'STU-1338', 'Theo Bright', 'zbt_e18s…Vw35', '7288114620', 'Connected', 'Nhắc lịch học — 8:00')
on conflict (id) do nothing;

insert into threads (id, from_name, role, subject, preview, time_label, unread) values
  (1, 'Daniel Cole', 'Math · Grade 9', 'Re: Jordan Ellis intervention plan', 'I met with Jordan after class today — he agreed to the Tuesday tutoring block. Can we loop in his parents before…', '12 min', true),
  (2, 'Nguyen family', 'Parent · Grade 10', 'Absence note for Thursday', 'Minh has a medical appointment Thursday morning and will miss first period. Attaching the clinic confirmation…', '1 h', true),
  (3, 'Rachel Park', 'English dept.', 'AP Literature enrollment list', 'Here is the final list of 12 candidates the AI flagged, with my notes on each. I disagree on two of them…', '3 h', false),
  (4, 'District Office', 'Announcement', 'Fall term reporting deadlines', 'Reminder: attendance and grade exports for the state report are due August 29. The new template is…', 'Yesterday', false),
  (5, 'Kenji Sato', 'CS · Grade 10', 'Lab 2 equipment request', 'Half of the keyboards in Lab 2 are failing. Requesting 12 replacements before the new term starts…', 'Yesterday', false)
on conflict (id) do nothing;

insert into app_settings (key, value) values
  ('zaloAuto', '{"attend": true, "grades": true, "tuition": true, "risk": false}'::jsonb)
on conflict (key) do nothing;

-- Đồng bộ lại identity sequence sau khi seed id thủ công
select setval(pg_get_serial_sequence('students', 'id'), (select coalesce(max(id), 1) from students));
select setval(pg_get_serial_sequence('payments', 'id'), (select coalesce(max(id), 1) from payments));
select setval(pg_get_serial_sequence('courses', 'id'), (select coalesce(max(id), 1) from courses));
select setval(pg_get_serial_sequence('schedule_sessions', 'id'), (select coalesce(max(id), 1) from schedule_sessions));
select setval(pg_get_serial_sequence('zalo_links', 'id'), (select coalesce(max(id), 1) from zalo_links));
select setval(pg_get_serial_sequence('threads', 'id'), (select coalesce(max(id), 1) from threads));
